# ----------------------------
# Makefile Options
# ----------------------------

NAME = ne
ICON = icon.png
DESCRIPTION = "Nano Extended editor"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Werror -Wall -Wextra -Oz -DCEDEV
CXXFLAGS = -Werror -Wall -Wextra -Oz - DCEDEV
LDHAS_ARG_PROCESSING = 0
LDHAS_EXIT_HANDLER:=0
# ----------------------------

include $(shell agondev-config --makefile)

