# ----------------------------
# Makefile Options
# ----------------------------

NAME = sort
ICON = icon.png
DESCRIPTION = "Utility to sort files"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Werror -Wall -Wextra -Oz -DCEDEV
CXXFLAGS = -Werror -Wall -Wextra -Oz - DCEDEV
LDHAS_ARG_PROCESSING = 1
LDHAS_EXIT_HANDLER:=0
# ----------------------------

include $(shell agondev-config --makefile)

