# ----------------------------
# Makefile Options
# ----------------------------

NAME = loadfont
ICON = icon.png
DESCRIPTION = "Utility to load fonts"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Werror -Wall -Wextra -Oz -DCEDEV
CXXFLAGS = -Werror -Wall -Wextra -Oz - DCEDEV
LDHAS_EXIT_HANDLER:=0
# ----------------------------

include $(shell agondev-config --makefile)

