# ----------------------------
# Makefile Options
# ----------------------------

NAME = recode
ICON = icon.png
DESCRIPTION = "Utility to covert text files between various encodings"
COMPRESSED = NO
ARCHIVED = NO
INIT_LOC = 040000
BSSHEAP_LOW = 050000
BSSHEAP_HIGH = 0B7FFF
STACK_HIGH = 0B7FFF

CFLAGS = -Werror -Wall -Wextra -Oz -DCEDEV
CXXFLAGS = -Werror -Wall -Wextra -Oz - DCEDEV
LDHAS_EXIT_HANDLER:=0
# ----------------------------

include $(shell cedev-config --makefile)

