# ----------------------------
# Makefile Options
# ----------------------------

NAME = recode
ICON = icon.png
DESCRIPTION = "Utility to covert text files between various encodings"
COMPRESSED = NO
ARCHIVED = NO
CFLAGS = -Werror -Wall -Wextra -Oz -DCEDEV
CXXFLAGS = -Werror -Wall -Wextra -Oz - DCEDEV
LDHAS_EXIT_HANDLER:=0
# ----------------------------

include $(shell agondev-config --makefile)

